# Generated by Django 4.0.3 on 2022-03-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Comforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.BooleanField(default=False, verbose_name='парковка')),
                ('gym', models.BooleanField(default=False, verbose_name='спортзал')),
                ('pool', models.BooleanField(default=False, verbose_name='бассейн')),
                ('beach', models.BooleanField(default=False, verbose_name='пляж')),
                ('meals', models.BooleanField(default=False, verbose_name='питание')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='сайт')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='email')),
                ('telephone', models.IntegerField(null=True, verbose_name='телефон')),
                ('rating', models.IntegerField(null=True, verbose_name='рейтинг')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsComforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comforts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.comforts')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.hotels')),
            ],
        ),
    ]
