# Generated by Django 4.0.3 on 2022-03-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='тип номера')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='цена номера')),
            ],
        ),
        migrations.RemoveField(
            model_name='comforts',
            name='gym',
        ),
        migrations.AddField(
            model_name='comforts',
            name='animals',
            field=models.BooleanField(default=False, verbose_name='животные'),
        ),
        migrations.AddField(
            model_name='comforts',
            name='animation',
            field=models.BooleanField(default=False, verbose_name='анимация'),
        ),
        migrations.AddField(
            model_name='comforts',
            name='fitness',
            field=models.BooleanField(default=False, verbose_name='фитнес'),
        ),
        migrations.AddField(
            model_name='comforts',
            name='medical',
            field=models.BooleanField(default=False, verbose_name='медуслуги'),
        ),
        migrations.AddField(
            model_name='comforts',
            name='spa',
            field=models.BooleanField(default=False, verbose_name='спа-комплекс'),
        ),
        migrations.AddField(
            model_name='comforts',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='трансфер'),
        ),
        migrations.AddField(
            model_name='comforts',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.CreateModel(
            name='RoomsComforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comforts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.comforts')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.hotels')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.rooms')),
            ],
        ),
    ]
